MealTimeOnline/Models/Consumer/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using MealTimeOnline.Models.Common;
using MealTimeOnline.Models.Dealer;

namespace MealTimeOnline.Models.Consumer
{
    public enum Satisfaction
    {
        [Display(Name = "好评")]
        Positive,

        [Display(Name = "中评")]
        Moderate,

        [Display(Name = "差评")]
        Negative
    }

    public enum OrderStatus
    {
        [Display(Name = "待处理")]
        Pending,

        [Display(Name = "处理中")]
        Processing,

        [Display(Name = "订单完成")]
        Complete,

        [Display(Name = "取消订单")]
        Cancel
    }

    public enum PayStatus
    {
        [Display(Name = "待支付")]
        Pending,

        [Display(Name = "已支付")]
        Completed
    }

    public class Order
    {
        [Key]
        public long OrderId { get; set; } // 定单号

        [Display(Name = "订单号")]
        public string OrderIdentificationCode // 订单唯一表示符
            => $"{OrderTime:yyyyMMddHHmmssFFFFFF}{UserId%10000:D4}{CanteenId%10000:D4}{OrderId%10000:D4}";

        [Required(ErrorMessage = "下单时间不能为空")]
        [Display(Name = "下单时间")]
        public DateTime OrderTime { get; set; } // 下单时间

        [Display(Name = "订单完成时间")]
        public DateTime? ComplateTime { get; set; } // 订单完成时间

        [Display(Name = "订单状态")]
        [Required(ErrorMessage = "订单状态不能为空")]
        public OrderStatus OrderStatus { set; get; } // 订单状态（待处理、完成、退单）

        [Display(Name = "订单支付状态")]
        [Required(ErrorMessage = "支付状态不能为空")]
        public PayStatus PayStatus { get; set; } // 订单支付状态（完成支付、待支付）

        [Required(ErrorMessage = "支付方式不能为空")]
        public int PaymentId { set; get; } // 订单支付方式（微信、支付宝、校园卡，//（线上财富值））
        public virtual Payment Payment { get; set; }

        [Display(Name = "满意度")]
        public Satisfaction? Satisfaction { set; get; } // 满意度（好评、差评）

        [Display(Name = "评价")]
        public virtual ICollection<Evaluate> Evaluates { get; set; } // 评价(有的存具体评价，没有自动填充“待评价”)

        [Display(Name = "订单数量")]
        [Required(ErrorMessage = "订单数量不能为空")]
        public int OrderNum { set; get; } // 订单数量

        [Display(Name = "总价")]
        [Required(ErrorMessage = "订单总价不能为空")]
        public decimal SumPrice { get; set; } // 总价

        [Display(Name = "用户")]
        [ForeignKey("User")]
        [Required(ErrorMessage = "用户不能为空")]
        public int UserId { get; set; }
        public virtual User User { get; set; } // 一个订单对应一个用户

        [Display(Name = "食堂")]
        [ForeignKey("Canteen")]
        [Required(ErrorMessage = "食堂不能为空")]
        public int CanteenId { get; set; }
        public virtual Canteen Canteen { get; set; } // 一个订单对应一个食堂

        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}

MealTimeOnline/Models/Dealer/Canteen.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using MealTimeOnline.Models.Commodity;
using MealTimeOnline.Models.Common;
using MealTimeOnline.Models.Consumer;

namespace MealTimeOnline.Models.Dealer
{
    // 主要用于展示给顾客，用于选择
    public class Canteen
    {
        // 商家基础信息
        [Key]
        public int CanteenId { get; set; } // 食堂编号（唯一）

        [Display(Name = "名称")]
        [StringLength(128)]
        public string CanteenName { get; set; } // 食堂名称

        [Display(Name = "地址")]
        [StringLength(1024)]
        public string CanteenAddress { get; set; } // 食堂地址

        [Display(Name = "分类")]
        public int? CanteenCategoryId { get; set; } // 食堂分类
        public virtual CanteenCategory CanteenCategory { get; set; }

        [Display(Name = "配送价格")]
        public decimal ServicePrice { get; set; } // 食堂配送价格

        [Display(Name = "介绍")]
        [StringLength(2048)]
        public string CanteenInfo { get; set; } // 食堂介绍

        [Display(Name = "配送方式")]
        [StringLength(256)]
        public string SendWay { get; set; } // 食堂配送方式

        [Display(Name = "营业时间")]
        [StringLength(256)]
        public string ShopHours { get; set; } // 形如：12：00-13：00 // 营业时间

        [Display(Name = "商家公告")]
        [StringLength(2048)]
        public string Notice { get; set; } // 商家公告

        // 基于用户评价的商家信息
        [Display(Name = "平均配餐时间")]
        public TimeSpan UseTime { get; set; } // 食堂平均配餐时间（分钟）

        [Display(Name = "平均打分")]
        [Range(typeof(decimal), "0", "5")]
        public decimal EvaluateNum { get; set; } // 食堂平均打分

        [Display(Name = "月销售量")]
        public int SellNum { get; set; } // 食堂月销售量

        [Display(Name = "图片")]
        public string Images { get; set; } // 一个食堂对应多个图片, 用Json数组保存图片地址

        public virtual List<Food> Foods { get; set; } // 一个食堂对应多个菜
        public virtual ICollection<Order> Orders { get; set; } // 一个食堂对应多个订单
        public virtual ICollection<Evaluate> Evaluates { get; set; } // 一个食堂对应多个评价
    }
}

MealTimeOnline/ViewModels/Order/CanteenViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MealTimeOnline.Models.Dealer;

namespace MealTimeOnline.ViewModels.Order
{
    #region 餐厅视图模型
    public class CanteenViewModel
    {
        public List<Canteen> canteen { get; set; } //餐厅列表
    }
    #endregion
}

MealTimeOnline/ViewModels/Order/CartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MealTimeOnline.ViewModels.Order
{
    #region 订单视图模型
    public class OrderViewModel
    {
        public int FoodId { get; set; } //食物id
        public int cnt { get; set; } //食物数量
    }
    #endregion

    #region 购物车视图模型
    public class CartViewModel
    {
        public int canteenId { get; set; } //餐厅id
        public List<OrderViewModel> orders { get; set; } //订单列表
    }
    #endregion
}

MealTimeOnline/ViewModels/Order/CheckOutViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MealTimeOnline.ViewModels.Order;
using MealTimeOnline.Models.Consumer;

namespace MealTimeOnline.ViewModels.Order
{
    public class CheckOutViewModel
    {
        public CartViewModel cartVm { get; set; } //购物车
        public decimal ServicePrice { get; set; } //配送费
        public decimal TotalPrice { get; set; } //总价
        //收货地址,付款方式. 未完成
    }
}

MealTimeOnline/Areas/Admin/Controllers/CanteensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MealTimeOnline.DataAccessLayer;
using MealTimeOnline.Models.Dealer;

namespace MealTimeOnline.Areas.Admin.Controllers
{
    public class CanteensController : Controller
    {
        private MtoDataContext db = new MtoDataContext();

        // GET: Admin/Canteens
        public ActionResult Index()
        {
            var canteens = db.Canteens.Include(c => c.CanteenCategory);
            return View(canteens.ToList());
        }

        // GET: Admin/Canteens/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Canteen canteen = db.Canteens.Find(id);
            if (canteen == null)
            {
                return HttpNotFound();
            }
            return View(canteen);
        }

        // GET: Admin/Canteens/Create
        public ActionResult Create()
        {
            ViewBag.CanteenCategoryId = new SelectList(db.CanteenCategories, "CanteenCategoryId", "Value");
            return View();
        }

        // POST: Admin/Canteens/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CanteenId,CanteenName,CanteenAddress,CanteenCategoryId,ServicePrice,CanteenInfo,SendWay,ShopHours,Notice,UseTime,EvaluateNum,SellNum,Images")] Canteen canteen)
        {
            if (ModelState.IsValid)
            {
                canteen.EvaluateNum = 5;
                db.Canteens.Add(canteen);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CanteenCategoryId = new SelectList(db.CanteenCategories, "CanteenCategoryId", "Value", canteen.CanteenCategoryId);
            return View(canteen);
        }

        // GET: Admin/Canteens/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Canteen canteen = db.Canteens.Find(id);
            if (canteen == null)
            {
                return HttpNotFound();
            }
            ViewBag.CanteenCategoryId = new SelectList(db.CanteenCategories, "CanteenCategoryId", "Value", canteen.CanteenCategoryId);
            return View(canteen);
        }

        // POST: Admin/Canteens/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CanteenId,CanteenName,CanteenAddress,CanteenCategoryId,ServicePrice,CanteenInfo,SendWay,ShopHours,Notice,UseTime,EvaluateNum,SellNum,Images")] Canteen canteen)
        {
            if (ModelState.IsValid)
            {
                db.Entry(canteen).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CanteenCategoryId = new SelectList(db.CanteenCategories, "CanteenCategoryId", "Value", canteen.CanteenCategoryId);
            return View(canteen);
        }

        // GET: Admin/Canteens/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Canteen canteen = db.Canteens.Find(id);
            if (canteen == null)
            {
                return HttpNotFound();
            }
            return View(canteen);
        }

        // POST: Admin/Canteens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Canteen canteen = db.Canteens.Find(id);
            db.Canteens.Remove(canteen);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MealTimeOnline/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.Drawing.Text;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Image = MealTimeOnline.Models.Common.Image;

namespace MealTimeOnline.Controllers
{
    public class ImageController : Controller
    {
        // GET: Image/Placeholder
        public ActionResult Placeholder(int width, int height, string text)
        {
            Bitmap res = new Bitmap(width, height);
            Graphics g = Graphics.FromImage(res);
            g.TextRenderingHint = TextRenderingHint.AntiAlias;
            g.FillRectangle(Brushes.LightGray, new Rectangle(0, 0, width, height));

            string str = text ?? $"{width}x{height}";

            float lo = 1f, hi = width / 2.5f;
            while ((hi - lo) > 1e-2)
            {
                float mid = (lo + hi) / 2f;
                SizeF sx = g.MeasureString(str, new Font("微软雅黑", mid));
                if (sx.Width < (width*0.92f) && sx.Height < (height*0.96f))
                    lo = mid;
                else
                    hi = mid;
            }

            Font font = new Font("微软雅黑", lo);
            SizeF size = g.MeasureString(str, font);

            g.DrawString(str, font, Brushes.Gray, (width - size.Width) / 2f, (height - size.Height) / 2f);
            MemoryStream ms = new MemoryStream();
            res.Save(ms, ImageFormat.Png);
            return File(ms.GetBuffer(), @"image/png");
        }
    }
}

MealTimeOnline/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MealTimeOnline.DataAccessLayer;
using MealTimeOnline.Models.Consumer;
using MealTimeOnline.Models.Dealer;
using MealTimeOnline.ViewModels.Order;
using MealTimeOnline.Models.Commodity;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace MealTimeOnline.Controllers
{
    #region 餐厅展示，下单控制器
    public class OrderController : Controller
    {
        MtoDataContext db = new MtoDataContext();
        public static CartViewModel cartVm = new CartViewModel();

        #region 餐厅展示
        // GET: Order/Canteen
        [HttpGet]
        public ActionResult Canteen()
        {
            cartVm.orders = new List<OrderViewModel>();
            CanteenViewModel canteenVm = new CanteenViewModel();
            canteenVm.canteen = db.Canteens.ToList(); //从数据库中获取餐厅数据，并初始化视图模型
            return View("Canteen", canteenVm);
        }
        #endregion

        //[HttpPost]
        //public void Canteen(string BtnSubmit)
        //{
        //    if (BtnSubmit == "CheckOut")
        //    {
        //        CheckOut(cartVm);
        //    }
        //}

        #region 点餐触发事件
        // POST: Order/Modify
        [HttpPost]
        public void Modify(string id, string cnt)//所点食物的id和数量cnt
        {
            cartVm.canteenId = db.Foods.Find(int.Parse(id)).CanteenId;
            if (id != string.Empty && cnt != string.Empty)
            {
                bool flag = false;
                for (int i = 0; i < cartVm.orders.Count; i++)
                {
                    if (int.Parse(id) == cartVm.orders[i].FoodId)
                    {
                        if (int.Parse(cnt) == 0)
                        {
                            cartVm.orders.RemoveAt(i);
                        }
                        else
                        {
                            cartVm.orders[i].cnt = int.Parse(cnt);
                        }
                        flag = true;
                        break;
                    }
                }
                if (flag == false)
                {
                    OrderViewModel item = new OrderViewModel();
                    item.FoodId = int.Parse(id); item.cnt = int.Parse(cnt);
                    cartVm.orders.Add(item);
                }
            }
        }
        #endregion

        #region 结算Action
        // POST: Order/CheckOut
        [HttpPost]
        public ActionResult CheckOut()
        {
            CheckOutViewModel checkVm = new CheckOutViewModel();
            checkVm.cartVm = cartVm;
            checkVm.TotalPrice = 0;
            checkVm.ServicePrice = db.Canteens.Find(cartVm.canteenId).ServicePrice;
            foreach (OrderViewModel item in cartVm.orders) //总计每个顶点的总计
            {
                checkVm.TotalPrice += item.cnt * db.Foods.Find(item.FoodId).Price;
            }
            checkVm.TotalPrice += checkVm.ServicePrice; //总计加上配送费
            return View("CheckOut", checkVm);
        }
        #endregion

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Submit(string orders)
        {
            CheckOutViewModel data = System.Web.Helpers.Json.Decode<CheckOutViewModel>(orders);

            int canteenId = data.cartVm.canteenId;
            int userId = int.Parse(HttpContext.User.Identity.Name);

            // Create order
            Order order = new Order
            {
                CanteenId = canteenId,
                OrderNum = data.cartVm.orders.Count,
                OrderTime = DateTime.Now,
                PaymentId = db.Payments.First().PaymentId,
                OrderStatus = OrderStatus.Pending,
                SumPrice = data.TotalPrice,
                UserId = userId
            };
            db.Orders.Add(order);
            db.SaveChanges();

            // Create order items
            foreach (var item in data.cartVm.orders)
            {
                OrderItem oi = new OrderItem
                {
                    CanteenId = canteenId,
                    UserId = userId,
                    Count = item.cnt,
                    FoodId = item.FoodId,
                    OrderId = order.OrderId,
                    Price = db.Foods.Find(item.FoodId).Price * item.cnt
                };
                db.OrderItems.Add(oi);
            }
            db.SaveChanges();

            return RedirectToAction("Index", "Account");
        }
    }
    #endregion
}

MealTimeOnline/Views/Order/Canteen.cshtml
@using MealTimeOnline.ViewModels.Order
@using MealTimeOnline.Models.Dealer
@using MealTimeOnline.Models.Commodity
@model CanteenViewModel

@{ViewBag.Title = "Canteen";}

<div class="container clearfix">

    <div class="navbar-left navbar-form">
        <span>Current location：</span>
        <span>
            <a href="#">2333</a>
        </span>
    </div>

    <div class="navbar-right navbar-form">
        <div class="input-group">
            <input class="search-input form-control" placeholder="Search foods" />
            <span class="input-group-addon"><i class="fa fa-search"></i></span>
        </div>
    </div>

    <div class="container-fluid">
        <div class="wrapper">
            <img src="@Url.Action("Placeholder", "Image", new { width = 1110, height = 100, text = "广告位长期招收" })" />
        </div>
    </div>

    <div class="container-fluid">
        <div class="Business-sorts">
            <span>食堂分类：</span>
            <ul>
                @for (int i = 0; i < Model.canteen.Count; ++i)
                {
                    <li><a class="@if(i==0) {@("current")}" href="#" onclick="showSelected(); showTab('rstbox', @(i));" @Model.canteen[i].CanteenId>@Model.canteen[i].CanteenName</a></li>
                }
            </ul>
        </div>

        <div class="row">
            @for (int j = 0; j < Model.canteen.Count; j++)
            {
                <div class="rstbox @if(j == 0) {@("rstbox-current")}">
                    @for (int k = 0; k < Model.canteen[j].Foods.Count; k++)
                    {
                        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                            <div class="food-box">
                                <img src="@Url.Action("Placeholder", "Image", new { width = 80, height = 80, text = Model.canteen[j].Foods[k].FoodName })" alt="food_01">
                                <div class="food-info">
                                    <a href="#" class="food-name">@Model.canteen[j].Foods[k].FoodName</a>
                                    <span class="food-star">
                                        <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-o"></i>
                                    </span>
                                    <span class="food-sale">月售xxxx单</span>
                                    <span class="food-cost"><i class="fa fa-rmb"></i> @Model.canteen[j].Foods[k].Price</span>
                                    <div class="food-cnt" data-food="@Model.canteen[j].Foods[k].FoodId" data-food-cnt="0" data-food-price="@Model.canteen[j].Foods[k].Price" data-food-name="@Model.canteen[j].Foods[k].FoodName">
                                        <div class="food-add-cart"><span>加入购物车</span></div>
                                        <div class="food-cart-cnt" hidden>
                                            <span class="pull-left">－</span>
                                            <input class="food-cart-num" title="" disabled value="1" />
                                            <span class="pull-right">＋</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            }
        </div>
    </div>
</div>

@*use js to control it*@

<div class="cart">
    <div id="cart-basket" class="cart-basket" style="top:-40px">
        <div class="cart-clear">
            Cart
            <a href="#" onclick="cartclear('footercheck')">[clear up]</a>
        </div>
        <div id="basic"></div>
    </div>
    <div class="cart-footer">
        <span><i class="fa fa-shopping-cart fa-2x" style="color:#fff;padding:10px"></i> <i class="fa fa-rmb fa-lg text-warning"></i></span>
        <span id="showprices" class="text-warning"></span>
        <form action="/Order/Checkout" method="post">
            <button type="submit" id="footercheck" class="cart-footer-check"><i class="fa fa-check"></i></button>
        </form>
    </div>
</div>

<script src="//cdn.bootcss.com/bootstrap/3.3.7/js/npm.js"></script>

MealTimeOnline/Views/Order/CheckOut.cshtml
@using MealTimeOnline.ViewModels.Order
@using MealTimeOnline.DataAccessLayer
@model CheckOutViewModel

@{
    ViewBag.Title = "CheckOut";
}

<div class="container" style="padding-top: 10px; padding-bottom: 10px">
    <div class="row">
        <div class="col-md-5 col-lg-5">
            <div class="panel panel-default">
                <div class="panel-heading">
                    订单详情
                </div>
                
                <div class="panel-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>商品</th>
                            <th>份数</th>
                            <th>小计(元)</th>
                        </tr>
                        </thead>

                        @{
                            var db = new MtoDataContext();
                        }

                        <tbody>
                        @foreach (OrderViewModel item in Model.cartVm.orders)
                        {
                            <tr>
                                <td>@db.Foods.Find(item.FoodId).FoodName</td>
                                <td>@item.cnt</td>
                                <td><i class="fa fa-rmb"></i> @(item.cnt * db.Foods.Find(item.FoodId).Price)</td>
                            </tr>
                        }
                        <tr>
                            <td>配送费</td>
                            <td>&nbsp;</td>
                            <td><i class="fa fa-rmb"></i> @Model.ServicePrice</td>
                        </tr>
                        </tbody>
                    </table>

                    <h1 class="pull-right text-danger">
                        <span class="small"><i class="fa fa-rmb text-danger"></i></span> @Model.TotalPrice
                    </h1>
                </div>
                
                <div class="panel-footer clearfix">
                    <span class="pull-right small">共 @Model.cartVm.orders.Count 份商品</span>
                </div>
            </div>
        </div>
        
        <div class="col-md-7 col-lg-7">
            <div class="panel panel-default">
                <div class="panel-heading"></div>
                <div class="panel-body">
                    @{
                        var usr = db.Users.Find(int.Parse(HttpContext.Current.User.Identity.Name));
                    }
                    <h4>收货地址</h4>
                    @usr.School @usr.RoomNum
                    
                    <h4>付款方式</h4>
                    @{ var first = true; }
                    <div class="row">
                        @foreach (var item in db.Payments)
                        {
                            <div class="col-sm-6 col-md-6">
                                <div style="border: 1px solid @if(first) {@("#0089dc") first = false;} else { @("#eee") }; padding: 10px; margin-top: 5px; margin-bottom: 5px">
                                    @item.Name
                                </div>
                            </div>
                        }
                    </div>
                    @using (Html.BeginForm("Submit", "Order", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        
                        <input type="hidden" id="orders" name="orders" value="@(Json.Encode(Model))" />

                        <button type="submit" class="btn btn-danger">提交订单</button>
                    }
                </div>
                <div class="panel-footer"></div>
            </div>
        </div>
    </div>
</div>